name: Publish to NPM
#on:
#  pull_request_target:
#    types:
#      - closed
#    branches:
#      - main
on:
  pull_request:
    branches: [main]
jobs:
  release:
    #if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'release/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "20"
      - name: publish npm
        working-directory: ./src/app/published-components
        run: |
          npm install typescript
          npm install --save-dev @types/react
          npm run build:typescript
          npm config set registry https://registry.npmjs.org/
          npm config set _authToken=${{secrets.NPM_TOKEN}}
          npm publish
